# Generated by Django 4.0 on 2021-12-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='distanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('dest', models.CharField(max_length=20)),
                ('distance', models.CharField(max_length=20)),
            ],
        ),
    ]
